"""empty message

Revision ID: 092966a33a30
Revises: 
Create Date: 2021-03-16 17:22:45.051592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '092966a33a30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_roles',
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role_name_kk', sa.String(length=180), nullable=False),
    sa.Column('role_name_ru', sa.String(length=180), nullable=False),
    sa.Column('role_key', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_id')
    )
    op.create_table('tbl_user_roles',
    sa.Column('user_role_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('roles_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('users_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('users_fullname', sa.String(length=180), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['tbl_roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_role_id'),
    sa.UniqueConstraint('user_role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user_roles')
    op.drop_table('tbl_roles')
    # ### end Alembic commands ###
