"""empty message

Revision ID: 0c05b5cac5ca
Revises: 092966a33a30
Create Date: 2021-03-16 17:26:01.184551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c05b5cac5ca'
down_revision = '092966a33a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tbl_roles', ['role_id'])
    op.create_unique_constraint(None, 'tbl_user_roles', ['user_role_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_user_roles', type_='unique')
    op.drop_constraint(None, 'tbl_roles', type_='unique')
    # ### end Alembic commands ###
