"""empty message

Revision ID: 1dbc8ba152f5
Revises: 0c05b5cac5ca
Create Date: 2021-03-16 17:34:42.126230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1dbc8ba152f5'
down_revision = '0c05b5cac5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_tasks',
    sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('task_title', sa.String(length=180), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_tasks')
    # ### end Alembic commands ###
