"""empty message

Revision ID: b5cd7c93b7cf
Revises: 1dbc8ba152f5
Create Date: 2021-03-16 18:28:35.239986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cd7c93b7cf'
down_revision = '1dbc8ba152f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_tasks', sa.Column('reminder', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'tbl_tasks', ['task_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_tasks', type_='unique')
    op.drop_column('tbl_tasks', 'reminder')
    # ### end Alembic commands ###
