"""empty message

Revision ID: df7a9a616135
Revises: 434312e97f82
Create Date: 2021-03-18 18:18:49.886842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7a9a616135'
down_revision = '434312e97f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_tasks', sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_tasks', 'create_time')
    # ### end Alembic commands ###
